### PR TITLE
Add option to remove "Open to LAN" & "Super Secret Settings" buttons

### PR DESCRIPTION
**Pull request by kotmatross28729**
I can’t say exactly what this is for, but I need it to avoid the OfflineAuth error: https://github.com/trollogyadherent/OfflineAuth/issues/15

Also available in config, disabled by default

Here's how it works in the game:
Before:

Desktop Screenshot 2023 07 25 - 19 54 08 22

After:

Desktop Screenshot 2023 07 25 - 19 45 27 41

### CODE REVIEW

**Comment by jss2a98aj** [comment]
This looks good at a glance. I will merge it in and test when I prep for the next update.

**Comment by Roadhog360** [comment]
You should make it gray out the buttons, instead of completely removing them. This way it doesn't appear as there are gaps in the UI button placement

**Comment by kotmatross28729** [comment]
@Roadhog360, do you want both buttons to be simply unclickable?
It's just that BugTorch has a function to `remove` the Broadcast Settings button, and not `turn it off`.
Here's what it might look like:
1Снимок

Снимок
?

**Comment by kotmatross28729** [comment]
Anyway I'll add the commit here for now, if there's something wrong, tell me and I can open the pull request again

**Pull request merged**
